# Generated by Django 2.2 on 2021-11-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211111_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
