# Generated by Django 2.2 on 2021-11-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish']},
        ),
    ]
