# Generated by Django 2.2 on 2021-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='super_user_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
